### ISSUE TITLE
UWP: City is always null

### ISSUE THREAD

**Issue by groege** [jamesmontemagno/ContactsPlugin#12]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

Version Number of Plugin: 2.2.0.24-beta
Device Tested On: Lumia 640XL Dual SIM
Simulator Tested On:

### Expected Behavior
The imported addresses should have all fields imported

### Actual Behavior
The City is never set in imported addresses

### Steps to reproduce the Behavior
Import an address with the "Ort" (German for Location which is equal to "City")

**Comment by jamesmontemagno** [comment]
@soroshsabz can you take a look at the automapper on this.

**Comment by soroshsabz** [comment]
ITNOA

@jamesmontemagno Yes :)

**Comment by soroshsabz** [comment]
@jamesmontemagno It seems locality in UWP `ContactAddress` represents city, so I map it to city in `Abstraction.Address` and test it and it works as you can see in PR. :)

**Comment by soroshsabz** [comment]
@jamesmontemagno Please update nuget package for resolved this problem in public era.

thx

**Comment by jamesmontemagno** [comment]
Just published: 2.2.0.29-beta
