### ISSUE TITLE
What is best code to check number present in contact list?

### ISSUE THREAD

**Issue by soroshsabz** [jamesmontemagno/ContactsPlugin#14]
ITNOA

I want to check phone number present in contact list or not very fast in Android? (phone number retrieve from phone call).

As you can see in [Android : Check phone number present in Contact List ? (Phone number retrieve from phone call)](http://stackoverflow.com/q/3505865/1539100). Android has some facilities to retrieve fast contacts from phone number.

So my question is how to write a query with `AddressBook` to behave like top section and very fast answer me?

Thanks

**Comment by soroshsabz** [comment]
@jamesmontemagno Do you have any suggestion about this?

thx

**Comment by jamesmontemagno** [comment]
urm... just tying it in a browser and not sure if it compiles at all something like:
```
contacts = CrossContacts.Current.Contacts
            .Where(c => c.Phones.Contains(p=> p.Number == number)) 
            .ToList();
```

**Comment by soroshsabz** [comment]
Thanks for your reply, is this query translate to some code like in my first post, and run without expensive performance cost?
