### ISSUE TITLE
Unable to install in UWP project

### ISSUE THREAD

**Issue by Yogeshk25** [jamesmontemagno/ContactsPlugin#16]
## Bug 

Version Number of Plugin: 2.2.0.9-beta
Device Tested On: 16-12-16
Simulator Tested On: 16-12-16

### Expected Behavior
Should have been installed

### Actual Behavior
Install failed with following errors,
Severity	Code	Description	Project	File	Line	Suppression State
Warning		Type universe cannot resolve assembly: System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.	AnalyticsTester.UWP			
Severity	Code	Description	Project	File	Line	Suppression State
Error		Package restore failed. Rolling back package changes for 'AnalyticsTester.UWP'.			0	
Severity	Code	Description	Project	File	Line	Suppression State
Warning		Cannot resolve Assembly or Windows Metadata file 'System.Runtime.dll'	AnalyticsTester.UWP	D:\Projects\AnalyticsTester\AnalyticsTester\AnalyticsTester.UWP\AnalyticsTester.UWP.csproj		

### Steps to reproduce the Behavior
Create a new xamarin form project
Add this plugin in UWP project

**Comment by jamesmontemagno** [comment]
Make sure to upgrade your UWP nuget itself
