### ISSUE TITLE
Contacts cannot be built for Release

### ISSUE THREAD

**Issue by rarera** [jamesmontemagno/ContactsPlugin#18]
## Bug 

* Version Number of Plugin:
  <package id="Xam.Plugin.Contacts" version="2.0.2-beta1" targetFramework="monoandroid60" />
* Device Tested On: Lenovo X1 Carbon
* Simulator Tested On: Visual Studio 2015 Enterprise 

### Expected Behavior
Build succeeded
### Actual Behavior
CS0234 The type or Namespace Contacts does not exist in the Namespace Plugin

### Steps to reproduce the Behavior
Create Android project
Add the listed plugin nugets
Use the nugets in code
Build for debug -> success
Build for release -> fails

**Comment by jamesmontemagno** [comment]
Are you sure your nugets are installed in all projects? What are your linker settings set to?

I have never had any issue and released several apps to the store without any issues.

**Comment by dimitrijevic** [comment]
Did you publish UWP apps?
