### ISSUE TITLE
UWP: No contacts found in release mode

### ISSUE THREAD

**Issue by groege** [jamesmontemagno/ContactsPlugin#19]
## Bug 
When compiling UWP for Store release ("Compile with .NET Native tool chain") the result will be empty (no exception, like no contacts would exist). It works however when "Compile with .NET Native tool chain" is disabled.
(Usually this flag isn't set in debug mode so it works when debugging, though when enabling the flagsin debug mode, no Contacts are found)

Version Number of Plugin: 2.2.0.29-beta
Device Tested On: Lumia 640XL Dual Sim
Simulator Tested On:

### Expected Behavior
Should retrieve Contacts the same way independent of set compiler flags.

### Actual Behavior
Does not retrieve Contacts when compiling for the Microsoft Store

### Steps to reproduce the Behavior
Enable "Compile with .NET Native tool chain" in an UWP-Project, build and query contacts.

**Comment by groege** [comment]
Maybe it has something to do with the AutoMapper?
Like i.e. they had a problem (though they did get Exceptions and this was Automapper 4.x not 5.x) https://github.com/AutoMapper/AutoMapper/issues/901

**Comment by dimitrijevic** [comment]
It's obviously got something to do with .NET native since it works in debug and not in release... But the time directives didn't help, or that we know off, since James said he published successfully elsewhere, I'm still hoping using UWP.
It'd be nice to know just how? Maybe Microsoft allows debug apps to be published for it's employees. They should let everyone do so then :(

**Comment by groege** [comment]
Thanks! Now it works for me too :)
Is there a way to make the contacts plugin do this automatically?

**Comment by dimitrijevic** [comment]
I've made a pull request, but haven't thoroughly tested, could you please, it's here: https://github.com/dimitrijevic/ContactsPlugin/edit/master/src/Contacts.Plugin.UWP/Properties/Plugin.Contacts.rd.xml

**Comment by groege** [comment]
I'm using this workaround for now too - thanks!

**Comment by dominik-weber** [comment]
I don't have much experience using rd.xml files, but this might be a more elegant solution:

    <Type Name="AutoMapper.Profile">
      <Method Name="CreateMap{TSource, TDestination}">
        <GenericParameter Name="TSource" Serialize="Required All" />
        <GenericParameter Name="TDestination" Serialize="Required All" />
      </Method>
    </Type>

I've added this to the `<Application>` node in my Default.rd.xml file. Suggestions welcome ;)

@jamesmontemagno we should probably add this to the lib as the issue currently breaks the functionality of store uploads for most users

**Comment by groege** [comment]
@dominik-weber  Ty  - works like a charm :)

**Comment by jamesmontemagno** [comment]
I have now removed automapper and manually transforming it :) I didn't work on the original UWP one so now it should be better.

**Comment by dominik-weber** [comment]
Works, thank you :)
