### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Yogeshk25** [jamesmontemagno/ContactsPlugin#21]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 
Unable to install in UWP project

Version Number of Plugin: 2.2.0.29-beta
Device Tested On:
Simulator Tested On:

### Expected Behavior
should be installed

### Actual Behavior
didn't installed

### Steps to reproduce the Behavior
make sure project.json file has followin entries
"runtimes": {
    "win10-arm": { },
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }

## Feature Request:
This happens because of AutoMapper dependency as it uses reflection which is not supported by aot platforms.
Suggestion is to remove AutoMapper.
I have already done that in a separate fork, will submit a PR soon.

**Comment by jamesmontemagno** [comment]
automapper will be removed in next release
