### ISSUE TITLE
Crashing on iOS

### ISSUE THREAD

**Issue by lengk** [jamesmontemagno/ContactsPlugin#24]
Including the NSContactsUsageDescription key in the info.plist file and using  Xamarin Forms 2.3.3.180

![info.plist](https://cloud.githubusercontent.com/assets/5440566/23333076/1a2300fc-fb7d-11e6-86a9-e76e1dceffa1.png)

I've added the package to the PCL Solution and iOS Solution, however the app is crashing on startup for iOS 10.2

**Comment by soroshsabz** [comment]
ITNOA

@lengk What is your version of ContactsPlugin? Can you tell what is exception occur? and in which line of sample code occur? ( for example line 4, when it try to fill `PreferContactAggregation`)

thanks

**Comment by lengk** [comment]
I think it was something to do with using iOS 7
